// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wolny.P.Infrastructure;

#nullable disable

namespace Wolny.P.Infrastructure.Migrations
{
    [DbContext(typeof(PContext))]
    partial class PContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Wolny.P.Domain.Camion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit");

                    b.Property<string>("Patente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Camiones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Disponible = false,
                            Patente = "XYZ0",
                            Ubicacion = "{\"latitud\":-34.6,\"longitud\":-58.37}"
                        },
                        new
                        {
                            Id = 2,
                            Disponible = true,
                            Patente = "ABC2",
                            Ubicacion = "{\"latitud\":-34.6,\"longitud\":-58.37}"
                        },
                        new
                        {
                            Id = 3,
                            Disponible = true,
                            Patente = "ABC3",
                            Ubicacion = "{\"latitud\":-34.6,\"longitud\":-58.37}"
                        },
                        new
                        {
                            Id = 4,
                            Disponible = true,
                            Patente = "ABC4",
                            Ubicacion = "{\"latitud\":-34.6,\"longitud\":-58.37}"
                        });
                });

            modelBuilder.Entity("Wolny.P.Domain.Ciudad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Distancias")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ciudades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Distancias = "{\"2\":646,\"3\":792,\"4\":933,\"5\":53,\"6\":986,\"7\":985,\"8\":989}",
                            Nombre = "CABA",
                            Ubicacion = "{\"latitud\":-34.6,\"longitud\":-58.37}"
                        },
                        new
                        {
                            Id = 2,
                            Distancias = "{\"1\":646,\"3\":677,\"4\":824,\"5\":698,\"6\":340,\"7\":466,\"8\":907}",
                            Nombre = "Córdoba",
                            Ubicacion = "{\"latitud\":-31.42,\"longitud\":-64.18}"
                        },
                        new
                        {
                            Id = 3,
                            Distancias = "{\"1\":792,\"2\":677,\"4\":157,\"5\":830,\"6\":814,\"7\":1131,\"8\":1534}",
                            Nombre = "Corrientes",
                            Ubicacion = "{\"latitud\":-27.47,\"longitud\":-58.83}"
                        },
                        new
                        {
                            Id = 4,
                            Distancias = "{\"1\":933,\"2\":824,\"3\":157,\"5\":968,\"6\":927,\"7\":1269,\"8\":1690}",
                            Nombre = "Formosa",
                            Ubicacion = "{\"latitud\":-26.18,\"longitud\":-58.17}"
                        },
                        new
                        {
                            Id = 5,
                            Distancias = "{\"1\":53,\"2\":698,\"3\":830,\"4\":968,\"6\":1038,\"7\":1029,\"8\":1005}",
                            Nombre = "La Plata",
                            Ubicacion = "{\"latitud\":-34.92,\"longitud\":-57.95}"
                        },
                        new
                        {
                            Id = 6,
                            Distancias = "{\"1\":986,\"2\":340,\"3\":814,\"4\":927,\"5\":1038,\"7\":427,\"8\":1063}",
                            Nombre = "La Rioja",
                            Ubicacion = "{\"latitud\":-29.41,\"longitud\":-66.85}"
                        },
                        new
                        {
                            Id = 7,
                            Distancias = "{\"1\":985,\"2\":466,\"3\":1131,\"4\":1269,\"5\":1029,\"6\":427,\"8\":676}",
                            Nombre = "Mendoza",
                            Ubicacion = "{\"latitud\":-32.88,\"longitud\":-68.84}"
                        },
                        new
                        {
                            Id = 8,
                            Distancias = "{\"1\":989,\"2\":907,\"3\":1534,\"4\":1690,\"5\":1005,\"6\":1063,\"7\":676}",
                            Nombre = "Neuquén",
                            Ubicacion = "{\"latitud\":-38.95,\"longitud\":-68.05}"
                        });
                });

            modelBuilder.Entity("Wolny.P.Domain.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CiudadId")
                        .HasColumnType("int");

                    b.Property<bool>("Entregado")
                        .HasColumnType("bit");

                    b.Property<int?>("RecorridoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CiudadId");

                    b.HasIndex("RecorridoId");

                    b.ToTable("Pedidos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CiudadId = 1,
                            Entregado = true
                        },
                        new
                        {
                            Id = 2,
                            CiudadId = 2,
                            Entregado = true
                        },
                        new
                        {
                            Id = 3,
                            CiudadId = 3,
                            Entregado = true
                        },
                        new
                        {
                            Id = 4,
                            CiudadId = 4,
                            Entregado = true
                        },
                        new
                        {
                            Id = 5,
                            CiudadId = 5,
                            Entregado = true
                        },
                        new
                        {
                            Id = 6,
                            CiudadId = 6,
                            Entregado = true
                        },
                        new
                        {
                            Id = 7,
                            CiudadId = 7,
                            Entregado = true
                        },
                        new
                        {
                            Id = 8,
                            CiudadId = 8,
                            Entregado = true
                        },
                        new
                        {
                            Id = 9,
                            CiudadId = 1,
                            Entregado = true
                        },
                        new
                        {
                            Id = 10,
                            CiudadId = 2,
                            Entregado = true
                        },
                        new
                        {
                            Id = 11,
                            CiudadId = 3,
                            Entregado = true
                        },
                        new
                        {
                            Id = 12,
                            CiudadId = 4,
                            Entregado = true
                        },
                        new
                        {
                            Id = 13,
                            CiudadId = 5,
                            Entregado = true
                        },
                        new
                        {
                            Id = 14,
                            CiudadId = 6,
                            Entregado = true
                        },
                        new
                        {
                            Id = 15,
                            CiudadId = 7,
                            Entregado = true
                        },
                        new
                        {
                            Id = 16,
                            CiudadId = 8,
                            Entregado = true
                        },
                        new
                        {
                            Id = 17,
                            CiudadId = 1,
                            Entregado = true
                        },
                        new
                        {
                            Id = 18,
                            CiudadId = 2,
                            Entregado = true
                        },
                        new
                        {
                            Id = 19,
                            CiudadId = 3,
                            Entregado = true
                        },
                        new
                        {
                            Id = 20,
                            CiudadId = 4,
                            Entregado = false
                        },
                        new
                        {
                            Id = 21,
                            CiudadId = 5,
                            Entregado = false
                        },
                        new
                        {
                            Id = 22,
                            CiudadId = 6,
                            Entregado = false
                        },
                        new
                        {
                            Id = 23,
                            CiudadId = 7,
                            Entregado = false
                        },
                        new
                        {
                            Id = 24,
                            CiudadId = 8,
                            Entregado = false
                        },
                        new
                        {
                            Id = 25,
                            CiudadId = 1,
                            Entregado = false
                        },
                        new
                        {
                            Id = 26,
                            CiudadId = 2,
                            Entregado = false
                        },
                        new
                        {
                            Id = 27,
                            CiudadId = 3,
                            Entregado = false
                        },
                        new
                        {
                            Id = 28,
                            CiudadId = 4,
                            Entregado = false
                        },
                        new
                        {
                            Id = 29,
                            CiudadId = 5,
                            Entregado = false
                        },
                        new
                        {
                            Id = 30,
                            CiudadId = 6,
                            Entregado = false
                        },
                        new
                        {
                            Id = 31,
                            CiudadId = 7,
                            Entregado = false
                        },
                        new
                        {
                            Id = 32,
                            CiudadId = 8,
                            Entregado = false
                        },
                        new
                        {
                            Id = 33,
                            CiudadId = 1,
                            Entregado = false
                        },
                        new
                        {
                            Id = 34,
                            CiudadId = 2,
                            Entregado = false
                        },
                        new
                        {
                            Id = 35,
                            CiudadId = 3,
                            Entregado = false
                        },
                        new
                        {
                            Id = 36,
                            CiudadId = 4,
                            Entregado = false
                        },
                        new
                        {
                            Id = 37,
                            CiudadId = 5,
                            Entregado = false
                        },
                        new
                        {
                            Id = 38,
                            CiudadId = 6,
                            Entregado = false
                        },
                        new
                        {
                            Id = 39,
                            CiudadId = 7,
                            Entregado = false
                        },
                        new
                        {
                            Id = 40,
                            CiudadId = 8,
                            Entregado = false
                        },
                        new
                        {
                            Id = 41,
                            CiudadId = 1,
                            Entregado = false
                        },
                        new
                        {
                            Id = 42,
                            CiudadId = 2,
                            Entregado = false
                        },
                        new
                        {
                            Id = 43,
                            CiudadId = 3,
                            Entregado = false
                        },
                        new
                        {
                            Id = 44,
                            CiudadId = 4,
                            Entregado = false
                        },
                        new
                        {
                            Id = 45,
                            CiudadId = 5,
                            Entregado = false
                        },
                        new
                        {
                            Id = 46,
                            CiudadId = 6,
                            Entregado = false
                        },
                        new
                        {
                            Id = 47,
                            CiudadId = 7,
                            Entregado = false
                        },
                        new
                        {
                            Id = 48,
                            CiudadId = 8,
                            Entregado = false
                        },
                        new
                        {
                            Id = 49,
                            CiudadId = 1,
                            Entregado = false
                        },
                        new
                        {
                            Id = 50,
                            CiudadId = 2,
                            Entregado = false
                        },
                        new
                        {
                            Id = 51,
                            CiudadId = 3,
                            Entregado = false
                        },
                        new
                        {
                            Id = 52,
                            CiudadId = 4,
                            Entregado = false
                        },
                        new
                        {
                            Id = 53,
                            CiudadId = 5,
                            Entregado = false
                        },
                        new
                        {
                            Id = 54,
                            CiudadId = 6,
                            Entregado = false
                        },
                        new
                        {
                            Id = 55,
                            CiudadId = 7,
                            Entregado = false
                        },
                        new
                        {
                            Id = 56,
                            CiudadId = 8,
                            Entregado = false
                        },
                        new
                        {
                            Id = 57,
                            CiudadId = 1,
                            Entregado = false
                        },
                        new
                        {
                            Id = 58,
                            CiudadId = 2,
                            Entregado = false
                        },
                        new
                        {
                            Id = 59,
                            CiudadId = 3,
                            Entregado = false
                        },
                        new
                        {
                            Id = 60,
                            CiudadId = 4,
                            Entregado = false
                        },
                        new
                        {
                            Id = 61,
                            CiudadId = 5,
                            Entregado = false
                        },
                        new
                        {
                            Id = 62,
                            CiudadId = 6,
                            Entregado = false
                        },
                        new
                        {
                            Id = 63,
                            CiudadId = 7,
                            Entregado = false
                        },
                        new
                        {
                            Id = 64,
                            CiudadId = 8,
                            Entregado = false
                        },
                        new
                        {
                            Id = 65,
                            CiudadId = 1,
                            Entregado = false
                        },
                        new
                        {
                            Id = 66,
                            CiudadId = 2,
                            Entregado = false
                        },
                        new
                        {
                            Id = 67,
                            CiudadId = 3,
                            Entregado = false
                        },
                        new
                        {
                            Id = 68,
                            CiudadId = 4,
                            Entregado = false
                        },
                        new
                        {
                            Id = 69,
                            CiudadId = 5,
                            Entregado = false
                        },
                        new
                        {
                            Id = 70,
                            CiudadId = 6,
                            Entregado = false
                        },
                        new
                        {
                            Id = 71,
                            CiudadId = 7,
                            Entregado = false
                        },
                        new
                        {
                            Id = 72,
                            CiudadId = 8,
                            Entregado = false
                        },
                        new
                        {
                            Id = 73,
                            CiudadId = 1,
                            Entregado = false
                        },
                        new
                        {
                            Id = 74,
                            CiudadId = 2,
                            Entregado = false
                        },
                        new
                        {
                            Id = 75,
                            CiudadId = 3,
                            Entregado = false
                        },
                        new
                        {
                            Id = 76,
                            CiudadId = 4,
                            Entregado = false
                        },
                        new
                        {
                            Id = 77,
                            CiudadId = 5,
                            Entregado = false
                        },
                        new
                        {
                            Id = 78,
                            CiudadId = 6,
                            Entregado = false
                        },
                        new
                        {
                            Id = 79,
                            CiudadId = 7,
                            Entregado = false
                        },
                        new
                        {
                            Id = 80,
                            CiudadId = 8,
                            Entregado = false
                        },
                        new
                        {
                            Id = 81,
                            CiudadId = 1,
                            Entregado = false
                        },
                        new
                        {
                            Id = 82,
                            CiudadId = 2,
                            Entregado = false
                        },
                        new
                        {
                            Id = 83,
                            CiudadId = 3,
                            Entregado = false
                        },
                        new
                        {
                            Id = 84,
                            CiudadId = 4,
                            Entregado = false
                        },
                        new
                        {
                            Id = 85,
                            CiudadId = 5,
                            Entregado = false
                        },
                        new
                        {
                            Id = 86,
                            CiudadId = 6,
                            Entregado = false
                        },
                        new
                        {
                            Id = 87,
                            CiudadId = 7,
                            Entregado = false
                        },
                        new
                        {
                            Id = 88,
                            CiudadId = 8,
                            Entregado = false
                        },
                        new
                        {
                            Id = 89,
                            CiudadId = 1,
                            Entregado = false
                        },
                        new
                        {
                            Id = 90,
                            CiudadId = 2,
                            Entregado = false
                        },
                        new
                        {
                            Id = 91,
                            CiudadId = 3,
                            Entregado = false
                        },
                        new
                        {
                            Id = 92,
                            CiudadId = 4,
                            Entregado = false
                        },
                        new
                        {
                            Id = 93,
                            CiudadId = 5,
                            Entregado = false
                        },
                        new
                        {
                            Id = 94,
                            CiudadId = 6,
                            Entregado = false
                        },
                        new
                        {
                            Id = 95,
                            CiudadId = 7,
                            Entregado = false
                        },
                        new
                        {
                            Id = 96,
                            CiudadId = 8,
                            Entregado = false
                        },
                        new
                        {
                            Id = 97,
                            CiudadId = 1,
                            Entregado = false
                        },
                        new
                        {
                            Id = 98,
                            CiudadId = 2,
                            Entregado = false
                        },
                        new
                        {
                            Id = 99,
                            CiudadId = 3,
                            Entregado = false
                        },
                        new
                        {
                            Id = 100,
                            CiudadId = 4,
                            Entregado = false
                        },
                        new
                        {
                            Id = 101,
                            CiudadId = 5,
                            Entregado = false
                        },
                        new
                        {
                            Id = 102,
                            CiudadId = 6,
                            Entregado = false
                        },
                        new
                        {
                            Id = 103,
                            CiudadId = 7,
                            Entregado = false
                        },
                        new
                        {
                            Id = 104,
                            CiudadId = 8,
                            Entregado = false
                        },
                        new
                        {
                            Id = 105,
                            CiudadId = 1,
                            Entregado = false
                        },
                        new
                        {
                            Id = 106,
                            CiudadId = 2,
                            Entregado = false
                        },
                        new
                        {
                            Id = 107,
                            CiudadId = 3,
                            Entregado = false
                        },
                        new
                        {
                            Id = 108,
                            CiudadId = 4,
                            Entregado = false
                        },
                        new
                        {
                            Id = 109,
                            CiudadId = 5,
                            Entregado = false
                        },
                        new
                        {
                            Id = 110,
                            CiudadId = 6,
                            Entregado = false
                        },
                        new
                        {
                            Id = 111,
                            CiudadId = 7,
                            Entregado = false
                        },
                        new
                        {
                            Id = 112,
                            CiudadId = 8,
                            Entregado = false
                        },
                        new
                        {
                            Id = 113,
                            CiudadId = 1,
                            Entregado = false
                        },
                        new
                        {
                            Id = 114,
                            CiudadId = 2,
                            Entregado = false
                        },
                        new
                        {
                            Id = 115,
                            CiudadId = 3,
                            Entregado = false
                        },
                        new
                        {
                            Id = 116,
                            CiudadId = 4,
                            Entregado = false
                        },
                        new
                        {
                            Id = 117,
                            CiudadId = 5,
                            Entregado = false
                        },
                        new
                        {
                            Id = 118,
                            CiudadId = 6,
                            Entregado = false
                        },
                        new
                        {
                            Id = 119,
                            CiudadId = 7,
                            Entregado = false
                        },
                        new
                        {
                            Id = 120,
                            CiudadId = 8,
                            Entregado = false
                        },
                        new
                        {
                            Id = 121,
                            CiudadId = 1,
                            Entregado = false
                        },
                        new
                        {
                            Id = 122,
                            CiudadId = 2,
                            Entregado = false
                        },
                        new
                        {
                            Id = 123,
                            CiudadId = 3,
                            Entregado = false
                        },
                        new
                        {
                            Id = 124,
                            CiudadId = 4,
                            Entregado = false
                        },
                        new
                        {
                            Id = 125,
                            CiudadId = 5,
                            Entregado = false
                        },
                        new
                        {
                            Id = 126,
                            CiudadId = 6,
                            Entregado = false
                        },
                        new
                        {
                            Id = 127,
                            CiudadId = 7,
                            Entregado = false
                        },
                        new
                        {
                            Id = 128,
                            CiudadId = 8,
                            Entregado = false
                        },
                        new
                        {
                            Id = 129,
                            CiudadId = 1,
                            Entregado = false
                        },
                        new
                        {
                            Id = 130,
                            CiudadId = 2,
                            Entregado = false
                        },
                        new
                        {
                            Id = 131,
                            CiudadId = 3,
                            Entregado = false
                        },
                        new
                        {
                            Id = 132,
                            CiudadId = 4,
                            Entregado = false
                        },
                        new
                        {
                            Id = 133,
                            CiudadId = 5,
                            Entregado = false
                        },
                        new
                        {
                            Id = 134,
                            CiudadId = 6,
                            Entregado = false
                        },
                        new
                        {
                            Id = 135,
                            CiudadId = 7,
                            Entregado = false
                        },
                        new
                        {
                            Id = 136,
                            CiudadId = 8,
                            Entregado = false
                        },
                        new
                        {
                            Id = 137,
                            CiudadId = 1,
                            Entregado = false
                        },
                        new
                        {
                            Id = 138,
                            CiudadId = 2,
                            Entregado = false
                        },
                        new
                        {
                            Id = 139,
                            CiudadId = 3,
                            Entregado = false
                        },
                        new
                        {
                            Id = 140,
                            CiudadId = 4,
                            Entregado = false
                        },
                        new
                        {
                            Id = 141,
                            CiudadId = 5,
                            Entregado = false
                        },
                        new
                        {
                            Id = 142,
                            CiudadId = 6,
                            Entregado = false
                        },
                        new
                        {
                            Id = 143,
                            CiudadId = 7,
                            Entregado = false
                        },
                        new
                        {
                            Id = 144,
                            CiudadId = 8,
                            Entregado = false
                        },
                        new
                        {
                            Id = 145,
                            CiudadId = 1,
                            Entregado = false
                        },
                        new
                        {
                            Id = 146,
                            CiudadId = 2,
                            Entregado = false
                        },
                        new
                        {
                            Id = 147,
                            CiudadId = 3,
                            Entregado = false
                        },
                        new
                        {
                            Id = 148,
                            CiudadId = 4,
                            Entregado = false
                        },
                        new
                        {
                            Id = 149,
                            CiudadId = 5,
                            Entregado = false
                        },
                        new
                        {
                            Id = 150,
                            CiudadId = 6,
                            Entregado = false
                        },
                        new
                        {
                            Id = 151,
                            CiudadId = 7,
                            Entregado = false
                        },
                        new
                        {
                            Id = 152,
                            CiudadId = 8,
                            Entregado = false
                        },
                        new
                        {
                            Id = 153,
                            CiudadId = 1,
                            Entregado = false
                        },
                        new
                        {
                            Id = 154,
                            CiudadId = 2,
                            Entregado = false
                        },
                        new
                        {
                            Id = 155,
                            CiudadId = 3,
                            Entregado = false
                        },
                        new
                        {
                            Id = 156,
                            CiudadId = 4,
                            Entregado = false
                        },
                        new
                        {
                            Id = 157,
                            CiudadId = 5,
                            Entregado = false
                        },
                        new
                        {
                            Id = 158,
                            CiudadId = 6,
                            Entregado = false
                        },
                        new
                        {
                            Id = 159,
                            CiudadId = 7,
                            Entregado = false
                        },
                        new
                        {
                            Id = 160,
                            CiudadId = 8,
                            Entregado = false
                        },
                        new
                        {
                            Id = 161,
                            CiudadId = 1,
                            Entregado = false
                        },
                        new
                        {
                            Id = 162,
                            CiudadId = 2,
                            Entregado = false
                        },
                        new
                        {
                            Id = 163,
                            CiudadId = 3,
                            Entregado = false
                        },
                        new
                        {
                            Id = 164,
                            CiudadId = 4,
                            Entregado = false
                        },
                        new
                        {
                            Id = 165,
                            CiudadId = 5,
                            Entregado = false
                        },
                        new
                        {
                            Id = 166,
                            CiudadId = 6,
                            Entregado = false
                        },
                        new
                        {
                            Id = 167,
                            CiudadId = 7,
                            Entregado = false
                        },
                        new
                        {
                            Id = 168,
                            CiudadId = 8,
                            Entregado = false
                        },
                        new
                        {
                            Id = 169,
                            CiudadId = 1,
                            Entregado = false
                        },
                        new
                        {
                            Id = 170,
                            CiudadId = 2,
                            Entregado = false
                        },
                        new
                        {
                            Id = 171,
                            CiudadId = 3,
                            Entregado = false
                        },
                        new
                        {
                            Id = 172,
                            CiudadId = 4,
                            Entregado = false
                        },
                        new
                        {
                            Id = 173,
                            CiudadId = 5,
                            Entregado = false
                        },
                        new
                        {
                            Id = 174,
                            CiudadId = 6,
                            Entregado = false
                        },
                        new
                        {
                            Id = 175,
                            CiudadId = 7,
                            Entregado = false
                        },
                        new
                        {
                            Id = 176,
                            CiudadId = 8,
                            Entregado = false
                        },
                        new
                        {
                            Id = 177,
                            CiudadId = 1,
                            Entregado = false
                        },
                        new
                        {
                            Id = 178,
                            CiudadId = 2,
                            Entregado = false
                        },
                        new
                        {
                            Id = 179,
                            CiudadId = 3,
                            Entregado = false
                        },
                        new
                        {
                            Id = 180,
                            CiudadId = 4,
                            Entregado = false
                        },
                        new
                        {
                            Id = 181,
                            CiudadId = 5,
                            Entregado = false
                        },
                        new
                        {
                            Id = 182,
                            CiudadId = 6,
                            Entregado = false
                        },
                        new
                        {
                            Id = 183,
                            CiudadId = 7,
                            Entregado = false
                        },
                        new
                        {
                            Id = 184,
                            CiudadId = 8,
                            Entregado = false
                        },
                        new
                        {
                            Id = 185,
                            CiudadId = 1,
                            Entregado = false
                        },
                        new
                        {
                            Id = 186,
                            CiudadId = 2,
                            Entregado = false
                        },
                        new
                        {
                            Id = 187,
                            CiudadId = 3,
                            Entregado = false
                        },
                        new
                        {
                            Id = 188,
                            CiudadId = 4,
                            Entregado = false
                        },
                        new
                        {
                            Id = 189,
                            CiudadId = 5,
                            Entregado = false
                        },
                        new
                        {
                            Id = 190,
                            CiudadId = 6,
                            Entregado = false
                        },
                        new
                        {
                            Id = 191,
                            CiudadId = 7,
                            Entregado = false
                        },
                        new
                        {
                            Id = 192,
                            CiudadId = 8,
                            Entregado = false
                        },
                        new
                        {
                            Id = 193,
                            CiudadId = 1,
                            Entregado = false
                        },
                        new
                        {
                            Id = 194,
                            CiudadId = 2,
                            Entregado = false
                        },
                        new
                        {
                            Id = 195,
                            CiudadId = 3,
                            Entregado = false
                        },
                        new
                        {
                            Id = 196,
                            CiudadId = 4,
                            Entregado = false
                        },
                        new
                        {
                            Id = 197,
                            CiudadId = 5,
                            Entregado = false
                        },
                        new
                        {
                            Id = 198,
                            CiudadId = 6,
                            Entregado = false
                        },
                        new
                        {
                            Id = 199,
                            CiudadId = 7,
                            Entregado = false
                        },
                        new
                        {
                            Id = 200,
                            CiudadId = 8,
                            Entregado = false
                        },
                        new
                        {
                            Id = 201,
                            CiudadId = 1,
                            Entregado = false
                        },
                        new
                        {
                            Id = 202,
                            CiudadId = 2,
                            Entregado = false
                        },
                        new
                        {
                            Id = 203,
                            CiudadId = 3,
                            Entregado = false
                        },
                        new
                        {
                            Id = 204,
                            CiudadId = 4,
                            Entregado = false
                        },
                        new
                        {
                            Id = 205,
                            CiudadId = 5,
                            Entregado = false
                        },
                        new
                        {
                            Id = 206,
                            CiudadId = 6,
                            Entregado = false
                        },
                        new
                        {
                            Id = 207,
                            CiudadId = 7,
                            Entregado = false
                        },
                        new
                        {
                            Id = 208,
                            CiudadId = 8,
                            Entregado = false
                        },
                        new
                        {
                            Id = 209,
                            CiudadId = 1,
                            Entregado = false
                        },
                        new
                        {
                            Id = 210,
                            CiudadId = 2,
                            Entregado = false
                        },
                        new
                        {
                            Id = 211,
                            CiudadId = 3,
                            Entregado = false
                        },
                        new
                        {
                            Id = 212,
                            CiudadId = 4,
                            Entregado = false
                        },
                        new
                        {
                            Id = 213,
                            CiudadId = 5,
                            Entregado = false
                        },
                        new
                        {
                            Id = 214,
                            CiudadId = 6,
                            Entregado = false
                        },
                        new
                        {
                            Id = 215,
                            CiudadId = 7,
                            Entregado = false
                        },
                        new
                        {
                            Id = 216,
                            CiudadId = 8,
                            Entregado = false
                        },
                        new
                        {
                            Id = 217,
                            CiudadId = 1,
                            Entregado = false
                        },
                        new
                        {
                            Id = 218,
                            CiudadId = 2,
                            Entregado = false
                        },
                        new
                        {
                            Id = 219,
                            CiudadId = 3,
                            Entregado = false
                        },
                        new
                        {
                            Id = 220,
                            CiudadId = 4,
                            Entregado = false
                        },
                        new
                        {
                            Id = 221,
                            CiudadId = 5,
                            Entregado = false
                        },
                        new
                        {
                            Id = 222,
                            CiudadId = 6,
                            Entregado = false
                        },
                        new
                        {
                            Id = 223,
                            CiudadId = 7,
                            Entregado = false
                        },
                        new
                        {
                            Id = 224,
                            CiudadId = 8,
                            Entregado = false
                        },
                        new
                        {
                            Id = 225,
                            CiudadId = 1,
                            Entregado = false
                        },
                        new
                        {
                            Id = 226,
                            CiudadId = 2,
                            Entregado = false
                        },
                        new
                        {
                            Id = 227,
                            CiudadId = 3,
                            Entregado = false
                        },
                        new
                        {
                            Id = 228,
                            CiudadId = 4,
                            Entregado = false
                        },
                        new
                        {
                            Id = 229,
                            CiudadId = 5,
                            Entregado = false
                        },
                        new
                        {
                            Id = 230,
                            CiudadId = 6,
                            Entregado = false
                        },
                        new
                        {
                            Id = 231,
                            CiudadId = 7,
                            Entregado = false
                        },
                        new
                        {
                            Id = 232,
                            CiudadId = 8,
                            Entregado = false
                        },
                        new
                        {
                            Id = 233,
                            CiudadId = 1,
                            Entregado = false
                        },
                        new
                        {
                            Id = 234,
                            CiudadId = 2,
                            Entregado = false
                        },
                        new
                        {
                            Id = 235,
                            CiudadId = 3,
                            Entregado = false
                        },
                        new
                        {
                            Id = 236,
                            CiudadId = 4,
                            Entregado = false
                        },
                        new
                        {
                            Id = 237,
                            CiudadId = 5,
                            Entregado = false
                        },
                        new
                        {
                            Id = 238,
                            CiudadId = 6,
                            Entregado = false
                        },
                        new
                        {
                            Id = 239,
                            CiudadId = 7,
                            Entregado = false
                        },
                        new
                        {
                            Id = 240,
                            CiudadId = 8,
                            Entregado = false
                        },
                        new
                        {
                            Id = 241,
                            CiudadId = 1,
                            Entregado = false
                        },
                        new
                        {
                            Id = 242,
                            CiudadId = 2,
                            Entregado = false
                        },
                        new
                        {
                            Id = 243,
                            CiudadId = 3,
                            Entregado = false
                        },
                        new
                        {
                            Id = 244,
                            CiudadId = 4,
                            Entregado = false
                        },
                        new
                        {
                            Id = 245,
                            CiudadId = 5,
                            Entregado = false
                        },
                        new
                        {
                            Id = 246,
                            CiudadId = 6,
                            Entregado = false
                        },
                        new
                        {
                            Id = 247,
                            CiudadId = 7,
                            Entregado = false
                        },
                        new
                        {
                            Id = 248,
                            CiudadId = 8,
                            Entregado = false
                        },
                        new
                        {
                            Id = 249,
                            CiudadId = 1,
                            Entregado = false
                        },
                        new
                        {
                            Id = 250,
                            CiudadId = 2,
                            Entregado = false
                        },
                        new
                        {
                            Id = 251,
                            CiudadId = 3,
                            Entregado = false
                        },
                        new
                        {
                            Id = 252,
                            CiudadId = 4,
                            Entregado = false
                        },
                        new
                        {
                            Id = 253,
                            CiudadId = 5,
                            Entregado = false
                        },
                        new
                        {
                            Id = 254,
                            CiudadId = 6,
                            Entregado = false
                        },
                        new
                        {
                            Id = 255,
                            CiudadId = 7,
                            Entregado = false
                        },
                        new
                        {
                            Id = 256,
                            CiudadId = 8,
                            Entregado = false
                        },
                        new
                        {
                            Id = 257,
                            CiudadId = 1,
                            Entregado = false
                        },
                        new
                        {
                            Id = 258,
                            CiudadId = 2,
                            Entregado = false
                        },
                        new
                        {
                            Id = 259,
                            CiudadId = 3,
                            Entregado = false
                        },
                        new
                        {
                            Id = 260,
                            CiudadId = 4,
                            Entregado = false
                        },
                        new
                        {
                            Id = 261,
                            CiudadId = 5,
                            Entregado = false
                        },
                        new
                        {
                            Id = 262,
                            CiudadId = 6,
                            Entregado = false
                        },
                        new
                        {
                            Id = 263,
                            CiudadId = 7,
                            Entregado = false
                        },
                        new
                        {
                            Id = 264,
                            CiudadId = 8,
                            Entregado = false
                        },
                        new
                        {
                            Id = 265,
                            CiudadId = 1,
                            Entregado = false
                        },
                        new
                        {
                            Id = 266,
                            CiudadId = 2,
                            Entregado = false
                        },
                        new
                        {
                            Id = 267,
                            CiudadId = 3,
                            Entregado = false
                        },
                        new
                        {
                            Id = 268,
                            CiudadId = 4,
                            Entregado = false
                        },
                        new
                        {
                            Id = 269,
                            CiudadId = 5,
                            Entregado = false
                        },
                        new
                        {
                            Id = 270,
                            CiudadId = 6,
                            Entregado = false
                        },
                        new
                        {
                            Id = 271,
                            CiudadId = 7,
                            Entregado = false
                        },
                        new
                        {
                            Id = 272,
                            CiudadId = 8,
                            Entregado = false
                        },
                        new
                        {
                            Id = 273,
                            CiudadId = 1,
                            Entregado = false
                        },
                        new
                        {
                            Id = 274,
                            CiudadId = 2,
                            Entregado = false
                        },
                        new
                        {
                            Id = 275,
                            CiudadId = 3,
                            Entregado = false
                        },
                        new
                        {
                            Id = 276,
                            CiudadId = 4,
                            Entregado = false
                        },
                        new
                        {
                            Id = 277,
                            CiudadId = 5,
                            Entregado = false
                        },
                        new
                        {
                            Id = 278,
                            CiudadId = 6,
                            Entregado = false
                        },
                        new
                        {
                            Id = 279,
                            CiudadId = 7,
                            Entregado = false
                        },
                        new
                        {
                            Id = 280,
                            CiudadId = 8,
                            Entregado = false
                        },
                        new
                        {
                            Id = 281,
                            CiudadId = 1,
                            Entregado = false
                        },
                        new
                        {
                            Id = 282,
                            CiudadId = 2,
                            Entregado = false
                        },
                        new
                        {
                            Id = 283,
                            CiudadId = 3,
                            Entregado = false
                        },
                        new
                        {
                            Id = 284,
                            CiudadId = 4,
                            Entregado = false
                        },
                        new
                        {
                            Id = 285,
                            CiudadId = 5,
                            Entregado = false
                        },
                        new
                        {
                            Id = 286,
                            CiudadId = 6,
                            Entregado = false
                        },
                        new
                        {
                            Id = 287,
                            CiudadId = 7,
                            Entregado = false
                        },
                        new
                        {
                            Id = 288,
                            CiudadId = 8,
                            Entregado = false
                        },
                        new
                        {
                            Id = 289,
                            CiudadId = 1,
                            Entregado = false
                        },
                        new
                        {
                            Id = 290,
                            CiudadId = 2,
                            Entregado = false
                        },
                        new
                        {
                            Id = 291,
                            CiudadId = 3,
                            Entregado = false
                        },
                        new
                        {
                            Id = 292,
                            CiudadId = 4,
                            Entregado = false
                        },
                        new
                        {
                            Id = 293,
                            CiudadId = 5,
                            Entregado = false
                        },
                        new
                        {
                            Id = 294,
                            CiudadId = 6,
                            Entregado = false
                        },
                        new
                        {
                            Id = 295,
                            CiudadId = 7,
                            Entregado = false
                        },
                        new
                        {
                            Id = 296,
                            CiudadId = 8,
                            Entregado = false
                        },
                        new
                        {
                            Id = 297,
                            CiudadId = 1,
                            Entregado = false
                        },
                        new
                        {
                            Id = 298,
                            CiudadId = 2,
                            Entregado = false
                        },
                        new
                        {
                            Id = 299,
                            CiudadId = 3,
                            Entregado = false
                        },
                        new
                        {
                            Id = 300,
                            CiudadId = 4,
                            Entregado = false
                        },
                        new
                        {
                            Id = 301,
                            CiudadId = 5,
                            Entregado = false
                        },
                        new
                        {
                            Id = 302,
                            CiudadId = 6,
                            Entregado = false
                        },
                        new
                        {
                            Id = 303,
                            CiudadId = 7,
                            Entregado = false
                        },
                        new
                        {
                            Id = 304,
                            CiudadId = 8,
                            Entregado = false
                        },
                        new
                        {
                            Id = 305,
                            CiudadId = 1,
                            Entregado = false
                        },
                        new
                        {
                            Id = 306,
                            CiudadId = 2,
                            Entregado = false
                        },
                        new
                        {
                            Id = 307,
                            CiudadId = 3,
                            Entregado = false
                        },
                        new
                        {
                            Id = 308,
                            CiudadId = 4,
                            Entregado = false
                        },
                        new
                        {
                            Id = 309,
                            CiudadId = 5,
                            Entregado = false
                        },
                        new
                        {
                            Id = 310,
                            CiudadId = 6,
                            Entregado = false
                        },
                        new
                        {
                            Id = 311,
                            CiudadId = 7,
                            Entregado = false
                        },
                        new
                        {
                            Id = 312,
                            CiudadId = 8,
                            Entregado = false
                        },
                        new
                        {
                            Id = 313,
                            CiudadId = 1,
                            Entregado = false
                        },
                        new
                        {
                            Id = 314,
                            CiudadId = 2,
                            Entregado = false
                        },
                        new
                        {
                            Id = 315,
                            CiudadId = 3,
                            Entregado = false
                        },
                        new
                        {
                            Id = 316,
                            CiudadId = 4,
                            Entregado = false
                        },
                        new
                        {
                            Id = 317,
                            CiudadId = 5,
                            Entregado = false
                        },
                        new
                        {
                            Id = 318,
                            CiudadId = 6,
                            Entregado = false
                        },
                        new
                        {
                            Id = 319,
                            CiudadId = 7,
                            Entregado = false
                        },
                        new
                        {
                            Id = 320,
                            CiudadId = 8,
                            Entregado = false
                        });
                });

            modelBuilder.Entity("Wolny.P.Domain.PlanRecorrido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CiudadId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Finalizado")
                        .HasColumnType("bit");

                    b.Property<int>("Prioridad")
                        .HasColumnType("int");

                    b.Property<int>("RecorridoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CiudadId");

                    b.HasIndex("RecorridoId");

                    b.ToTable("PlanRecorridos");
                });

            modelBuilder.Entity("Wolny.P.Domain.Recorrido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CamionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Finalizado")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CamionId");

                    b.ToTable("Recorridos");
                });

            modelBuilder.Entity("Wolny.P.Domain.Pedido", b =>
                {
                    b.HasOne("Wolny.P.Domain.Ciudad", "Ciudad")
                        .WithMany()
                        .HasForeignKey("CiudadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wolny.P.Domain.Recorrido", "Recorrido")
                        .WithMany("Pedidos")
                        .HasForeignKey("RecorridoId");

                    b.Navigation("Ciudad");

                    b.Navigation("Recorrido");
                });

            modelBuilder.Entity("Wolny.P.Domain.PlanRecorrido", b =>
                {
                    b.HasOne("Wolny.P.Domain.Ciudad", "Ciudad")
                        .WithMany("PlanRecorridos")
                        .HasForeignKey("CiudadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wolny.P.Domain.Recorrido", "Recorrido")
                        .WithMany("PlanRecorridos")
                        .HasForeignKey("RecorridoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ciudad");

                    b.Navigation("Recorrido");
                });

            modelBuilder.Entity("Wolny.P.Domain.Recorrido", b =>
                {
                    b.HasOne("Wolny.P.Domain.Camion", "Camion")
                        .WithMany()
                        .HasForeignKey("CamionId");

                    b.Navigation("Camion");
                });

            modelBuilder.Entity("Wolny.P.Domain.Ciudad", b =>
                {
                    b.Navigation("PlanRecorridos");
                });

            modelBuilder.Entity("Wolny.P.Domain.Recorrido", b =>
                {
                    b.Navigation("Pedidos");

                    b.Navigation("PlanRecorridos");
                });
#pragma warning restore 612, 618
        }
    }
}
